# Selected automatically for -DRUUVI_VARIANT=longlife; no GATT or history.
CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_EXT_ADV=y
CONFIG_POLL=y
CONFIG_BT_PERIPHERAL=n
CONFIG_BT_DIS=n
CONFIG_SENSOR=y
CONFIG_GPIO=y
CONFIG_WATCHDOG=y
CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_PICOLIBC=y
CONFIG_LOG=n
